commit message
js-tasks-ru/jsbasic-20230428_natalliakrup pull request #2
Opened 2023-05-03 10:03 UTC by natallia-krupnik

<img width="641" alt="Screenshot 2023-05-03 at 12 03 01" src="https://user-images.githubusercontent.com/85348795/235887388-cb89655d-5543-464e-86a1-16bf76c5260b.png">

2023-05-03 10:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-03 13:46 UTC, SinimaWath commented
- Надо решить все добавленные задачи
- По условию задачи, name может быть `null`, в твоем случае, код падает с ошибкой.

2023-05-03 19:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-04 09:15 UTC, SinimaWath requested changes

2023-05-04 09:15 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  } return false;
`return str.toLowerCase().includes('1xbet') || str.toLowerCase().includes('xxx')`. Так как includes возвращает true/false, нет смысла в if

2023-05-08 21:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-10 10:14 UTC, SinimaWath approved these changes

2023-05-10 10:16 UTC, merged